#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=charm;use_native_gui=false", "id=belt;use_native_gui=false", "id=body;use_native_gui=false"]

